//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachChiTieu
    {
        public int MaChiTieu { get; set; }
        public string TenChiTieu { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaLoai { get; set; }
    
        public virtual LoaiChiTieu LoaiChiTieu { get; set; }
    }
}
